
<?php
if(isset($_GET['score'])) {

    $score = $_GET['score'];

    header('Content-Type: text/plain');
    header('Content-Disposition: attachment; filename="SmartHire_Report.txt"');

    echo "SMART HIRE AI REPORT\n";
    echo "=====================\n\n";
    echo "Resume Score: " . $score . "%\n\n";

    if($score >= 80){
        echo "Status: Excellent Resume\n";
    } elseif($score >= 50){
        echo "Status: Good but needs improvement\n";
    } else {
        echo "Status: Needs major improvement\n";
    }

    echo "\nGenerated by SmartHire AI";
}
?>
